# Autoformatter friendly markdownlint config (all formatting rules disabled)
default: true
blank_lines: false
ul-style:
  style: "asterisk"
html: false
indentation: false
line_length: false
spaces: false
url: false
whitespace: false
